#!/bin/bash

# Quick reference for testing the O2 CMS API

echo "🧪 O2 CMS API Testing Guide"
echo "════════════════════════════════════════════"
echo ""
echo "To test the Environments API, you need:"
echo "  1. An API Key (from CMS Settings > API Keys)"
echo "  2. A Space ID (project ID)"
echo ""
echo "Available test scripts:"
echo ""
echo "  1. test-environments-api.sh"
echo "     Full CRUD test suite with error cases"
echo "     $ ./test-environments-api.sh <API_KEY> <SPACE_ID>"
echo ""
echo "  2. run-all-tests.sh"
echo "     Master test runner (runs all test suites)"
echo "     $ ./run-all-tests.sh <API_KEY> <SPACE_ID>"
echo ""
echo "  3. test-manual-curl.sh"
echo "     Shows manual cURL command examples"
echo "     $ ./test-manual-curl.sh <API_KEY> <SPACE_ID>"
echo ""
echo "════════════════════════════════════════════"
echo ""
echo "Quick test example:"
echo "  export API_KEY='o2_cma_your_key_here'"
echo "  export SPACE_ID='your-project-id'"
echo "  ./test-environments-api.sh \$API_KEY \$SPACE_ID"
echo ""
echo "API Base URL:"
echo "  https://us-central1-t4u-cms.cloudfunctions.net/api"
echo ""
echo "Current Implementation (Phase 2):"
echo "  ✓ Environments API (GET/POST/PUT/DELETE)"
echo "  - Content Types API (Next)"
echo "  - Entries API (Next)"
echo "  - Assets API (Next)"
echo "  - Locales API (Next)"
echo ""

